require 'rails3-jquery-autocomplete'
require 'best_in_place'
require 'simple_form'
require 'bluecloth'
require 'cocoon'
require 'bootstrap-sass'
require 'tabulous'
require 'kaminari'
require 'kaminari-bootstrap'
require 'cornell-assemblies-rails/rails'
require 'cornell-assemblies-rails/core_ext/big_decimal'
require 'cornell-assemblies-rails/core_ext/float'
require 'cornell-assemblies-rails/core_ext/integer'
require 'cornell-assemblies-rails/core_ext/string'
require 'cornell-assemblies-rails/core_ext/array'

